BUGFIX: handling negative values
Sometimes binja returns big numbers as negative values in LLIL_CONST .

The script failed then because L is used:
error: integer out of range for 'L' format code

Switching to 'l' fixes it
(does the whole unpack/pack still make sense then?)